### ISSUE TITLE
v0.8.0-alpha.2 not published as a crate

### ISSUE THREAD

**Issue by MicLeey** [ory/kratos-client-rust#2]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/kratos-client-rust/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/kratos-client-rust/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Looks like the latest version of the SDK was generated, but not published as a crate

### Reproducing the bug

https://crates.io/crates/ory-kratos-client/versions

### Version

0.7.6

**Comment by aeneasr** [comment]
fixed
